# Generated by Django 4.1.5 on 2023-01-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
