# Generated by Django 4.1.5 on 2023-01-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_cartoons_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_l', models.CharField(max_length=255)),
                ('two_l', models.CharField(max_length=255)),
                ('three_l', models.CharField(max_length=255)),
            ],
        ),
    ]
